# LINK ./product.model.ts
components:
    schemas:
        Product:
            type: object
            properties:
                _id:
                    type: string
                    description: "A termék azonosítója - elsődleges kulcs (ObjectId)"
                    example: "dddd00000000000000000000"
                product_name:
                    type: string
                    description: "A termék neve"
                    example: "jonatán alma"
                picture_url:
                    type: string
                    description: "A termék képének URL címe"
                    example: "https://i.imgur.com/jiGsYNz.jpg"
                category_id:
                    type: string
                    pattern: "^[0-9a-fA-F]{24}$"
                    description: "A termékhez tartozó kategória ID - FK"
                    example: "cccc00000000000000000008"
                category:
                    $ref: "#/components/schemas/Category"
                
